---
title: "Assignment"
description: |
  To use visual analytics to detect anomalies and suspicious behavior in movement and tracking data.
author:
  - name: Nurulasyiqah Md. Taha
    url: https://www.linkedin.com/in/nurulasyiqah-md-taha/
date: 07-13-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.retina=3,
                      echo = FALSE, 
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

## 1. Introduction

[**VAST Challenge 2021 - The Kronos Incident (Mini-Challenge 2)**](https://vast-challenge.github.io/2021/index.html)

Between 20-21 Jan 2014, on the island country of Kronos, several employees of GAStech, a Tethys gas multinational, go missing.

To get to the bottom of this mystery, we will use visual analytic techniques to analyze data provided by GAStech to assist with law enforcement’s investigation and hopefully find the missing persons and bring them home safely. The data provided by GAStech covering the two weeks prior to the GAStech employees’ disappearance are as follows:

* GAStech employee’s credit card transactions and Kronos Kares loyalty card data, and
* Movement and tracking data from GAStech’s company cars which have GPS tracking.

## 2. Objective

The objective of this project is to use visual analytic techniques to surface and identify anomalies and suspicious behavior. 

## 3. Literature review

### 3.1 Previous work

Since VAST Challenge 2021 is a redux of [**VAST Challenge 2014**](http://visualdata.wustl.edu/varepository/VAST%20Challenge%202014/challenges/MC2%20-%20Patterns%20of%20Life%20Analysis/) with some variation, modified data and new questions, we reviewed past submissions for Mini-Challenge 2 for some inspiration on tackling this year's challenge.

We were particularly drawn to the following submissions:

* The [**DAC-MC2 team from Virginia Tech**](http://visualdata.wustl.edu/varepository/VAST%20Challenge%202014/challenges/MC2%20-%20Patterns%20of%20Life%20Analysis/entries/Virginia%20Tech) used a methodology called Points of Interest (**“POI”**) to identify POIs such as people’s homes, their work places, and recreational locations (e.g. restaurants, cafes). A location is considered a POI if the time spent at a location is more than 5 minutes and the location has a diameter of less than 50 meters. They then graphed the distribution of POI over time for various days (weekdays and weekends) and locations (i.e. home, work, recreation).

* Similarly, the [**MiddlesexMASS-Attfield-MC2 team from Middlesex University**](http://visualdata.wustl.edu/varepository/VAST%20Challenge%202014/challenges/MC2%20-%20Patterns%20of%20Life%20Analysis/entries/Middlesex%20University) used the Patterns of Life (**“POL”**) suite to create a map showing where each person was at any given time and for how long. They also overlayed credit card and loyalty transactions over their map.

* To better understand the credit card and loyalty card data, the [**IIITH-YASHASWI-MC2 team from the International Institute of Information Technology Hyderabad**](http://visualdata.wustl.edu/varepository/VAST%20Challenge%202014/challenges/MC2%20-%20Patterns%20of%20Life%20Analysis/entries/International%20Institute%20of%20Information%20Technology%20Hyderabad) visualized the distributions of credit card transactions by date and by person and employment title / employee title. This analysis enabled them to better understand typical patterns and identify transactions that deviated and stood out.

* The [**Purdue-Guo-MC2 team from Purdue University**](http://visualdata.wustl.edu/varepository/VAST%20Challenge%202014/challenges/MC2%20-%20Patterns%20of%20Life%20Analysis/entries/Purdue%20University) created a **Social Relationship Matrix**, which involves plotting a heatmap of the number of times GAStech employees meet each other over the course of the two weeks. The assumption is that the more frequent people meet, the closer relationship they have between them.

Eager to reproduce and improve the visualisations, we looked further into the dataset provided for the 2014 Challenge. While the datasets provided in 2014 were generally similar, we noted a significant difference in the 2021 datasets: Both the credit card transactions data and loyalty card transactions data do not reflect the name of the card holders.

This presents a further challenge for us to reproduce the inspiring visualisations above (especially the Social Relationship Matrix) and we have to consider alternatives or adaptations in some cases.

### 3.2 R Graph Gallery

We browsed the [R Graph Gallery](https://www.r-graph-gallery.com/index.html) for ideas on various types of charts and graphs that can be visualised using relevant R packages.

### 3.3 R packages

## 4. Data preparation

### 4.1 Data cleaning

### 4.2 Geo-referencing

As the Abila, Kronos, tourist map image file provided (MC2-tourist.jpg) does not have coordinates projection, we need to perform geo-referencing. We used a geographic information system software, [QGIS](https://www.qgis.org/en/site/index.html), to geo-reference the image file with the Abila shapefile (in WGS84 coordinates) to obtain a geo-referenced tourist map (MC2-tourist.tif).

## 5. Visual analysis

### 5.1 Using just the credit and loyalty card data, identify the most popular locations, and when they are popular. What anomalies do you see? What corrections would you recommend to correct these anomalies?


### 5.2 Add the vehicle data to your analysis of the credit and loyalty card data. How does your assessment of the anomalies in question 1 change based on this new data? What discrepancies between vehicle, credit, and loyalty card data do you find?

### 5.3 Can you infer the owners of each credit card and loyalty card? What is your evidence? Where are there uncertainties in your method? Where are there uncertainties in the data?


### 5.4 Given the data sources provided, identify potential informal or unofficial relationships among GASTech personnel. Provide evidence for these relationships.


### 5.5 Do you see evidence of suspicious activity? Identify 1- 10 locations where you believe the suspicious activity is occurring, and why.

